CREATE TABLE [dbo].[RECORD_LABEL]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[LABEL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCATION] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ALBUM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECORD_LABEL] ADD CONSTRAINT [PK__RECORD_L__3214EC2744C2324F] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
