CREATE TABLE [dbo].[GAMES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GENRE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMPLETED] [bit] NULL CONSTRAINT [DF__GAMES__COMPLETED__2D47B39A] DEFAULT ((0)),
[RATING] [tinyint] NULL,
[PLATFORM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUBLISHER] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GAMES] ADD CONSTRAINT [PK__GAMES__3214EC27C1766EC0] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
